name: "Composite action"
description: "Composite action"

inputs:
  argument-a:
    description: "argument-a"
    required: true
  argument-b:
    description: "argument-b"
    required: true

runs:
  using: composite
  steps:

  - name: call add node action
    uses: ./add-node-action
    with:
      argument-a: ${{ inputs.argument-a }}
      argument-b: ${{ inputs.argument-b }}

  - name: call add docker action
    uses: ./add-docker-action
    with:
      argument-a: ${{ inputs.argument-a }}
      argument-b: ${{ inputs.argument-b }}
