name: "Node action x"
description: "Node action x"

inputs:
  github-username:
    description: "github-username"
    required: true
  github-token:
    description: "github-token"
    required: true

outputs:
  github-email:
    description: "github-email"

runs:
  using: node20
  main: main.js
