name: "Node action"
description: "Node action"

inputs:
  github-token:
    description: "github-token"
    required: true
  github-username:
    description: "github-username"
    required: true

runs:
  using: node24
  main: main.js
